### ISSUE TITLE
Accessing discovery URL failed: bad uri

### ISSUE THREAD

**Issue by mineiro** [oktadeveloper/okta-kong-origin-example#1]
Hi guys!

I'm trying to follow the guide but I'm having a problem on the last step.

When I try to access http://localhost:8000 the following message is returned:

`accessing discovery url ('redacted for security reasons...') failed: bad uri: 'https://tentant redacted for security reasons/oauth2/default/.well-known/openid-configuration'
`

Can you point me into any direction?

By the way, loving your platform.

Thanks! 🙏

**Comment by dogeared** [comment]
Hey @mineiro - Are you using the `default` authorization server? If not, you'll need to replace the `/default/` part of the authorization server with the id of the authorization server you are using.

**Comment by mineiro** [comment]
Hi @dogeared ! Yes, the default AS.

I'm tinkering around to see if I can find something. But until now, no success.

Tks!

**Comment by dogeared** [comment]
Let's do a screenshare. I am available after noon, eastern time, US

**Comment by viplovedev** [comment]
Hi Micah, Getting the same error. How do I know which authorization server I'm using?

> Hey @mineiro - Are you using the default authorization server? If not, you'll need to replace the /default/ part of the authorization server with the id of the authorization server you are using.

accessing discovery url ("https://dev-xxxxxx-admin.okta.com/oauth2/default/.well-known/openid-configuration") failed: bad uri

**Comment by viplovedev** [comment]
Hi @dogeared , Getting the same error. How do I know which authorization server I'm using?

> Hey @mineiro - Are you using the default authorization server? If not, you'll need to replace the /default/ part of the authorization server with the id of the authorization server you are using.

accessing discovery url ("https://dev-xxxxxx-admin.okta.com/oauth2/default/.well-known/openid-configuration") failed: bad uri

**Comment by mraible** [comment]
@viplovedev Remove "-admin" from your URL and it should work.

**Comment by viplovedev** [comment]
@mraible :  it's the same error for that as well. 
accessing discovery url ("https://dev-xxxxxx.okta.com/oauth2/default/.well-known/openid-configuration") failed: bad uri

**Comment by mraible** [comment]
Are you sure you have a developer account and not an IT Trial account? My developer account works:

https://dev-133320.okta.com/oauth2/default/.well-known/openid-configuration

If you have an IT Trial account, you can sign up for a free developer account at https://developer.okta.com/signup.

**Comment by dogeared** [comment]
I've done a major update to this repo with the latest and greatest.
