### ISSUE TITLE
Dockerfile fails to build

### ISSUE THREAD

**Issue by taahir-hassem** [oktadeveloper/okta-kong-origin-example#2]
I'm having an issue building the Kong image, Docker fails to build with the following error:

`Step 6/11 : RUN luarocks install kong-oidc`
` ---> Running in 335bcd245ef5`
`/bin/sh: luarocks: command not found`
`The command '/bin/sh -c luarocks install kong-oidc' returned a non-zero code: 127`

Am I missing something?

**Comment by merou** [comment]
luarocks package is not installed by default on centos:7, can be fetch adding epel repo.

Working example:

FROM centos:7
MAINTAINER Micah Silverman, micah.silverman@okta.com

ENV KONG_VERSION 0.11.1

RUN yum install -y wget https://bintray.com/kong/kong-community-edition-rpm/download_file?file_path=centos/7/kong-community-edition-$KONG_VERSION.el7.noarch.rpm

RUN yum install epel-release -y && yum clean all
RUN yum install -y git unzip openssl openssl-devel gcc lua-devel luarocks && yum clean all
RUN luarocks install kong-oidc

COPY docker-entrypoint.sh /docker-entrypoint.sh
ENTRYPOINT ["/docker-entrypoint.sh"]

EXPOSE 8000 8443 8001 8444

STOPSIGNAL SIGTERM

CMD ["kong", "docker-start"]

**Comment by dogeared** [comment]
I've done a major update to this repo with the latest and greatest.
